Integrated release evaluation

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,10 +1,8 @@
-name: 'infra-test'
+name: Pipeline Test
 on: push
+
 jobs:
-  infra-test:
-    permissions:
-      contents: write
-      pull-requests: write
+  pipe-test:
     runs-on: ubuntu-24.04
     steps:
 
@@ -37,13 +35,13 @@ jobs:
         run: poetry run dvc pull
     
       - name: Perform experiment
-        run: poetry run dvc exp run --name infra-test
+        run: poetry run dvc exp run --name pipe-test
 
       - name: Check accuracy
         run: |
-          acc=$(poetry run dvc exp show --csv | grep "infra-test" | awk -F ',' '{$6}')
+          acc=$(poetry run dvc exp show --csv | grep "pipe-test" | awk -F ',' '{$6}')
           if [ -z "$acc" ]; then
-              echo "No accuracy found for infra-test"
+              echo "No accuracy found for pipe-test"
               STATUS=1
           fi
           if (( $(echo "$acc < 0.1" | bc -l) )); then
@@ -54,20 +52,56 @@ jobs:
               STATUS=0
           fi
           echo "STATUS=$STATUS" >> $GITHUB_ENV
-    
+  
+      - name: List releases
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: gh release list
+
+      - name: Download releases
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "${GITHUB_REF_NAME}"
+          gh release download v0.1.7-beta -p "Sentiment_Analysis_Model.joblib"
+          gh release download v0.1.7-beta -p "Sentiment_Analysis_Preprocessor.joblib"
+        
+      - name: Check if files exist
+        run: |
+          if [ ! -f "Sentiment_Analysis_Model.joblib" ]; then
+              echo "Sentiment_Analysis_Model.joblib not found"
+              STATUS=1
+          fi
+          if [ ! -f "Sentiment_Analysis_Preprocessor.joblib" ]; then
+              echo "Sentiment_Analysis_Preprocessor.joblib not found"
+              STATUS=1
+          fi
+          echo "STATUS=$STATUS" >> $GITHUB_ENV
+        
+      - name: Check model
+        run: |
+          poetry run python -c "
+          import joblib
+          model = joblib.load('Sentiment_Analysis_Model.joblib')
+          preprocessor = joblib.load('Sentiment_Analysis_Preprocessor.joblib')
+          dummy = ['This is a test sentence.']
+          X = preprocessor.transform(dummy)
+          pred = model.predict(X.toarray())
+          " || echo "1=$STATUS" >> $GITHUB_ENV
+          
       - name: Set badge
         run: |
           if [ $STATUS -eq 0 ]; then
-              poetry run anybadge --label=pipeline --value=healthy --color=green --file=infra-test-badge.svg
+              poetry run anybadge --label=pipeline --value=healthy --color=green --file=pipe_test_badge.svg
           else
-              poetry run anybadge --label=pipeline --value=failed --color=red --file=infra-test-badge.svg
+              poetry run anybadge --label=pipeline --value=failed --color=red --file=pipe_test_badge.svg
           fi
   
       - name: Upload badge
         uses: actions/upload-artifact@v4
         with:
-          name: infra-test-badge
-          path: infra-test-badge.svg
+          name: pipe_test_badge
+          path: pipe_test_badge.svg
           compression-level: 0
           overwrite: true
   
@@ -82,9 +116,9 @@ jobs:
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           mkdir -p badges
-          mv infra-test-badge.svg badges/infra-test-badge.svg
-          git add badges/infra-test-badge.svg
-          git commit -m "Update infra-test-badge" || true # see below
+          mv pipe_test_badge.svg badges/pipe_test_badge.svg
+          git add badges/pipe_test_badge.svg
+          git commit -m "Update pipe_test_badge" || true # see below
           git push || true  # adding true statement to avoid error on "nothing to commit"
     
       - name: Exit with status
